config/routes.rb
Rails.application.routes.draw do

  resources :restaurants do
    resources :comments
  end

  resources :otp_restaurants do
    resources :comments
  end

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :atlanta,
	          :inclusion => { :in => [true, false] }
	# validates :name, presence: true,
	# 									length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	http_basic_authenticate_with name: "goose", password: "secret", only: :destroy

	def create
		@restaurant = Restaurant.find(params[:restaurant_id])
		@comment = @restaurant.comments.create(comment_params)
		redirect_to restaurant_path(@restaurant)
	end

	def destroy
		@restaurant = Restaurant.find(params[:restaurant_id])
		@comment = @restaurant.comments.find(params[:id])
		@comment.destroy
		redirect_to restaurant_path(@restaurant)
	end

	private
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/otp_restaurants_controller.rb
class OtpRestaurantsController < ApplicationController

	http_basic_authenticate_with name: "goose", password: "secret", except: [:index, :show]

	def index
		@otp_restaurants = Restaurant.all
	end

	def show
		@otp_restaurant = Restaurant.find(params[:id])
	end

	def edit
		@otp_restaurant = Restaurant.find(params[:id])
	end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

	http_basic_authenticate_with name: "goose", password: "secret", except: [:index, :show]

	def index
		@restaurants = Restaurant.all
	end

	def show
		@restaurant = Restaurant.find(params[:id])
	end

	def new
		@restaurant = Restaurant.new
	end

	def edit
		@restaurant = Restaurant.find(params[:id])
	end

	def create
		@restaurant = Restaurant.new(restaurant_params)

		if @restaurant.save
			redirect_to @restaurant
		else
			render 'new'
		end
	end

	def update
		@restaurant = Restaurant.find(params[:id])

		if @restaurant.update(restaurant_params)
			redirect_to @restaurant
		else
			render 'edit'
		end
	end

	def destroy
		@restaurant = Restaurant.find(params[:id])
	  @restaurant.destroy

	  redirect_to restaurants_path
	end

	private
		def restaurant_params
			params.require(:restaurant).permit(:name, :address, :website, :order, :thoughts, :atlanta)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/otp_restaurant_helper.rb
module OtpRestaurantHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
	<%= link_to 'Destroy Comment', [comment.restaurant, comment],
	               method: :delete,
	               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@restaurant, @restaurant.comments.build]) do |f| %>
	<p>
		<%= f.label :commenter %><br>
		<%= f.text_field :commenter %>
	</p>
	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body%>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>radical nosh</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Serif|Roboto+Slab&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Bangers&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Coming+Soon&display=swap" rel="stylesheet">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/otp_restaurants/index.html.erb
<h2>Not Atlanta Restaurants</h2>

<%= link_to 'New restaurant', new_restaurant_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
  </tr>

  <% @otp_restaurants.each do |restaurant| %>
    <tr>
      <% if !restaurant.atlanta?  %>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.thoughts %></td>
        <td><%= link_to 'Show', restaurant_path(restaurant) %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant_path(restaurant),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/otp_restaurants/show.html.erb
<!-- <% if !@otp_restaurant.atlanta? %> -->
	<p>
		<strong>Name:</strong>
		<%= @restaurant.name %>
	</p>

	<p>
		<strong>Address:</strong>
		<%= @restaurant.address %>
	</p>

	<p>
		<strong>Website:</strong>
		<%= @restaurant.website %>
	</p>

	<p>
		<strong>Order:</strong>
		<%= @restaurant.order %>
	</p>

	<div>
		<%= image_tag(@restaurant.picture) %>
	</div>

	<p>
		<strong>Thoughts:</strong>
		<%= @restaurant.thoughts %>
	</p>
<!-- <% end %> -->


<h2>Comments</h2>
<%= render @restaurant.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>

  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@restaurant.errors.count, "error") %> prohibited
        this restaurant from being saved:
      </h2>
      <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

	<p>
		<%= f.label :name %><br>
		<%=	f.text_field :name %>
	</p>
  <p>
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </p>
  <p>
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </p>
  <p>
    <%= f.label :order %><br>
    <%= f.text_field :order %>
  </p>
	<p>
		<%= f.label :thoughts %> <br>
		<%= f.text_area :thoughts %>
	</p>
  <p>
    <%= f.label :atlanta %> <br>
    <%= f.radio_button :atlanta, true %> In ATL
    <%= f.radio_button :atlanta, false  %> Not in ATL
  </p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/restaurants/edit.html.erb
<h2>Editing restaurants</h2>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h2>Listing Atlanta Restaurants</h2>

<%= link_to 'New restaurant', new_restaurant_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
  </tr>

  <% @restaurants.each do |restaurant| %>
    <tr>
      <% if restaurant.atlanta? %>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.thoughts %></td>
        <td><%= link_to 'Show', restaurant_path(restaurant) %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant_path(restaurant),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/restaurants/new.html.erb
<h2>Add a restaurant</h2>

<%= render 'form', post: @post %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p>
	<strong>Name:</strong>
	<%= @restaurant.name %>
</p>

<p>
	<strong>Address:</strong>
	<%= @restaurant.address %>
</p>

<p>
	<strong>Website:</strong>
	<%= @restaurant.website %>
</p>

<p>
	<strong>Order:</strong>
	<%= @restaurant.order %>
</p>

<div>
	<%= image_tag(@restaurant.picture) %>
</div>

<p>
	<strong>Thoughts:</strong>
	<%= @restaurant.thoughts %>
</p>


<h2>Comments</h2>
<%= render @restaurant.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

app/views/welcome/index.html.erb
<div id = homepage-container >
	<h1>radical nosh</h1>
	<h2>mouthfeel 101</h2>
	<div id = "snacklanta-link" class = "landing-page-link-box" >
		<%= link_to 'Snacklanta', controller: 'restaurants' %>
	</div>

	<div id = "notatl-link" class = "landing-page-link-box" >
		<%= link_to 'Not ATL', controller: 'otp_restaurants' %>
	</div>

	<div id = "recipes-link" class = "landing-page-link-box" >
		<%= link_to "table d'hote" %>
	</div>
</div>